services:
  db:
    image: postgres:14-alpine
    hostname: db
    ports:
        - '5432:5432'
    environment:
        - POSTGRES_PASSWORD=postgres
    volumes:
        - ./backend/verLaCartaBackup.sql:/docker-entrypoint-initdb.d/verLaCartaBackup.sql


  backend:
    depends_on:
      - db
    image: astro-bistro
    hostname: backend
    ports:
      - "5001:5001"
    env_file: backend/.env
    entrypoint: ["npm", "run", "backend"]

  frontend-consumidor:
    depends_on:
      - backend
    image: astro-bistro
    hostname: frontend-consumidor
    ports:
      - "4321:4321"
    environment:
      - BACKEND_URL=http://backend:5001
      - PUBLIC_BACKEND_URL=http://localhost:5001
      - PUBLIC_SOCKET_URL=http://localhost:5001
    entrypoint: ["npm", "run", "consumidorFE"]

  frontend-restaurante:
    depends_on:
      - backend
    image: astro-bistro
    hostname: frontend-restaurante
    ports:
      - "4322:4321"
    environment:
      - BACKEND_URL=http://backend:5001
      - PUBLIC_BACKEND_URL=http://localhost:5001
      - PUBLIC_SOCKET_URL=http://localhost:5001
    entrypoint: ["npm", "run", "restauranteFE"]
