services:
    db:
        image: postgres:14-alpine
        hostname: db
        ports:
            - '3333:5432'
        environment:
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./backend/verLaCartaBackup.sql:/docker-entrypoint-initdb.d/verLaCartaBackup.sql
