services:
  db:
    image: postgres:14-alpine
    hostname: db
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env.postgres
    volumes:
      - ./backend/verLaCarta_dump.sql:/docker-entrypoint-initdb.d/verLaCartaDump.sql
 
