name: Deploy Application

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.14
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PRIVATE_KEY }}
        script: |
          cd /root/astro-bistro/
          git pull origin main
          docker-compose down
          docker build -t astro-bistro .
          docker compose -f docker-compose-digitalocean.yaml up

